# Generated by Django 5.1.1 on 2024-09-11 10:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_shopuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
