# Generated by Django 5.1.1 on 2024-09-11 13:03

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_shopuser_options_remove_shopuser_date_joined_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ عضویت'),
        ),
    ]
