# Generated by Django 5.1.1 on 2024-09-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(default=0, verbose_name='وزن محصول'),
        ),
        migrations.AlterField(
            model_name='product',
            name='new_price',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='قیمت پس از تخفیف'),
        ),
        migrations.AlterField(
            model_name='product',
            name='off',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='تخفیف'),
        ),
    ]
